drop domain if exists LOG_LEVEL_ENUM;

create domain if not exists LOG_LEVEL_ENUM as enum (
  error = 'error',
  warning = 'warning',
  trace = 'trace'
) not null
  annotations(ecription 'Lits the logging level primary use for Table LOG_TAB')
;

drop table if exists LOG_TAB;

create table LOG_TAB (
  LOG_TAB_ID       integer generated by default as identity annotations (Description 'Primary key', Visibility 'ui_Hidden'),
  log_level        domain LOG_LEVEL_ENUM not null,
  cur_time         timestamp default systimestamp not null,
  msg              varchar2(4000) not null,
  program_unit     varchar2(300),
  session_user     varchar2(100) default sys_context('USERENV', 'SESSION_USER') not null,
  sid              integer default sys_context('USERENV', 'SID') not null,
  sessionid        integer default sys_context('USERENV', 'SESSIONID') not null,
  action           varchar2(200) default sys_context('USERENV', 'ACTION') not null,
  current_user     varchar2(100) default sys_context('USERENV', 'CURRENT_USER') not null
)
annotations (description 'Logging table')
;

alter table LOG_TAB
  add constraint pk_LOG_TAB
  primary key (LOG_TAB_id);


