drop domain if exists created_time_d;
create domain created_time_d as date
  default sysdate
  not null
  annotations (
    system_generated,
    description          'Creation date (with time) of this entry.',
    visibility        'ui_hidden'
  );
------------------------------------------------------------------------------------------------------------------------
drop domain if exists updated_time_d;
create domain updated_time_d as date
  annotations (
    system_generated,
    description          'The date (with time) of the last change of this entry.',
    visibility        'ui_hidden'
  );
------------------------------------------------------------------------------------------------------------------------
drop domain if exists updated_counter_d;
create domain updated_counter_d as integer
  default 1
  not null
  annotations (
    system_generated,
    description          'The version counter for this entry. Can be used to realize optimistic locking.',
    visibility        'ui_hidden'
  );
------------------------------------------------------------------------------------------------------------------------
drop domain if exists deleted_time_d;
create domain deleted_time_d as date
  annotations (
  system_generated,
  description          'The timestamp when this entry was virtualy deleted.',
  visibility        'ui_hidden'
);
------------------------------------------------------------------------------------------------------------------------
drop domain if exists CHA_OPERATIONAL_STATUS_ENUM;
create domain if not exists CHA_OPERATIONAL_STATUS_ENUM as enum (
  InBetrieb = 'In Betrieb',
  InWartung = 'In Wartung'
);
------------------------------------------------------------------------------------------------------------------------
drop domain if exists CHA_TYPE_OF_CHARGING_STATION_ENUM;

create domain if not exists CHA_TYPE_OF_CHARGING_STATION_ENUM as enum (
  NORMALLADEEINRICHTUNG = 'Normalladeeinrichtung',
  SCHNELLLADEEINRICHTUNG = 'Schnellladeeinrichtung'
);
------------------------------------------------------------------------------------------------------------------------
drop domain if exists CHA_OPENING_HOURS_ENUM;

create domain if not exists CHA_OPENING_HOURS_ENUM as enum (
  TwentyFourSeven = '247',
  Eingeschraenkt = 'Eingeschränkt',
  KeineAngabe = 'Keine Angabe'
);
------------------------------------------------------------------------------------------------------------------------
drop table if exists CHA_CHARGING_STATION;
create table CHA_CHARGING_STATION (
  CHA_CHARGING_STATION_ID       integer generated by default as identity annotations (Description 'Primary key', Visibility 'ui_Hidden'),
  
  CHA_CHARGING_STATION_ext_id       integer not null     annotations (Description 'ID der Ladesäule (Bundesnetzagentur-interne Nummer)'),
  operator_companyname              varchar2(200)        annotations (Description 'Betreiber der Ladesäule, Firmenname'),
  operator_displayname              varchar2(200)        annotations (Description 'Anzeigename des Betreibers'),
  status_operational                domain CHA_OPERATIONAL_STATUS_ENUM annotations (Description 'Status der Ladesäule'),
  station_type                      domain CHA_TYPE_OF_CHARGING_STATION_ENUM annotations (Description 'Art der Ladesäule'),
  location_description              varchar2(100)        annotations (Description 'Standortbezeichnung'),
  street                            varchar2(200)        annotations (Description 'Straßenname der Ladesäule'),
  house_no                          varchar2(50)         annotations (Description 'Hausnummer der Ladesäule'),
  address_addition                  varchar2(200)        annotations (Description 'Adresszusatz'),
  city                              varchar2(200)        annotations (Description 'Stadt der Ladesäule'),
  postal_code                       varchar2(20)         annotations (Description 'Postleitzahl der Ladesäule'),
  district_independent_city         varchar2(100)        annotations (Description 'Kreis/kreisfreie Stadt'),
  state                             varchar2(200)        annotations (Description 'Bundesland der Ladesäule'),
  latitude                          number               annotations (Description 'Breitengrad des Standortes'),
  longitude                         number               annotations (Description 'Längengrad des Standortes'),
  geo                               sdo_geometry not null annotations (Description 'Der Standort der Ladestation'),
  payment_systems                   json                  annotations (Description 'Bezahlsysteme'),
  access_restriction                varchar2(100)         annotations (Description 'Informationen zum Parkraum'),
  go_live_date                      date                  annotations (Description 'Inbetriebnahmedatum'),
  opening_hours_specification       domain CHA_OPENING_HOURS_ENUM annotations (Description 'Angabe der Öffnungszeiten'),
  opening_days                      json                  annotations (Description 'Tagebezogene Öffnungszeiten'),
  max_electric_power_station_in_kw  number               annotations (Description 'Nennleistung Ladeeinrichtung [kW]'),
  evse                              json                  annotations (Description 'Ladepunktbeschreibung'),
              
  created_dt                        domain created_time_d,
  updated_dt                        domain updated_time_d,
  updated_counter                   domain updated_counter_d
)
annotations (description 'Describes all charging station in Germany. The source is Bundesnetzargentur.')
;

alter table CHA_CHARGING_STATION
  add constraint pk_CHA_CHARGING_STATION
  primary key (CHA_CHARGING_STATION_id);

alter table CHA_CHARGING_STATION
  add constraint uk1_CHA_CHARGING_STATION 
  unique (CHA_CHARGING_STATION_ext_id);
  
delete from user_sdo_geom_metadata
  where table_name = upper('CHA_CHARGING_STATION')
    and column_name = upper('geo');
insert into user_sdo_geom_metadata (table_name, column_name, diminfo, srid)
  values (upper('CHA_CHARGING_STATION'), upper('geo'), sdo_dim_array(sdo_dim_element('longitude', -180, 180, 0.5), sdo_dim_element('latitude', -90, 90, 0.5)), 4326);
create index ids1_CHA_CHARGING_STATION on CHA_CHARGING_STATION(geo) indextype is mdsys.spatial_index_v2;
create or replace trigger tbu_CHA_CHARGING_STATION
  before update on CHA_CHARGING_STATION
  for each row
  begin
    :new.updated_dt       := sysdate;
    :new.updated_counter  := :old.updated_counter + 1;
  end;
/

