CREATE ROLE CONNECT1;

GRANT ALTER SESSION TO CONNECT1;
GRANT CREATE CLUSTER TO CONNECT1;
GRANT CREATE PROCEDURE TO CONNECT1;
GRANT CREATE SEQUENCE TO CONNECT1;
GRANT CREATE SESSION TO CONNECT1;
GRANT CREATE SYNONYM TO CONNECT1;
GRANT CREATE TABLE TO CONNECT1;
GRANT CREATE TRIGGER TO CONNECT1;
GRANT CREATE TYPE TO CONNECT1;
GRANT CREATE VIEW TO CONNECT1;
GRANT RESOURCE TO CONNECT1;
GRANT DEBUG CONNECT SESSION TO CONNECT1;
GRANT CREATE JOB TO connect1;
grant create domain to connect1;

